# Generated by Django 5.2.5 on 2025-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscam', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
