# Generated by Django 5.2.5 on 2025-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasscam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
